language: go
before_install:
    - pushd $HOME
    - wget -q https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-1.9.6.zip 
    - unzip -q go_appengine_sdk_linux_amd64-1.9.6.zip
    - cd go_appengine
    - export GAE=$(pwd)
    - popd
    - npm install -g grunt-cli
    - git clone git://github.com/n1k0/casperjs.git ~/casperjs
    - cd ~/casperjs
    - git checkout tags/1.0.2
    - export PATH=$PATH:`pwd`/bin
    - cd -
install:
    - cd $TRAVIS_BUILD_DIR
    - export GOPATH=$TRAVIS_BUILD_DIR
    - export GOHOME=$GAE
    - export PATH=$GAE:$PATH
    - which go
    - go env
    - go get github.com/gorilla/mux 
    - go get github.com/oleiade/reflections
script:
    - goapp serve &
    - casperjs test tests/admin.go.js

